# Generated by Django 4.1.5 on 2023-02-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("cal", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("ingridients", models.CharField(max_length=256)),
                ("weight", models.IntegerField()),
                ("products", models.ManyToManyField(to="web.product")),
            ],
        ),
        migrations.CreateModel(
            name="Cook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("prep_date", models.DateTimeField()),
                (
                    "id_dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.dish"
                    ),
                ),
            ],
        ),
    ]
